import { expect, test } from "@playwright/test"
import { abrirProyectoE2E, crearClaseNombradaE2E, crearProyectoE2E } from "./ayudas/proyectos"

test("atributo guiado conserva tipo y visibilidad privada después de guardar", async ({ page }) => {
  const proyecto = await crearProyectoE2E(page, "Atributo seguro")
  await crearClaseNombradaE2E(page, "Cliente")
  await page.getByTestId("inspector-propiedades").getByRole("button", { name: "+ Agregar atributo" }).click()
  const nuevo = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Nuevo atributo" })
  expect(await nuevo.getByLabel("Tipo").locator("option").allTextContents()).not.toContain("strin")
  await nuevo.getByLabel("Nombre").fill("nombre")
  await nuevo.getByLabel("Tipo").selectOption("String")
  await expect(nuevo.getByLabel("Visibilidad")).toHaveValue("privada")
  await nuevo.getByRole("button", { name: "Confirmar atributo" }).click()
  const existente = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Atributo nombre" })
  await expect(existente).toBeVisible()
  await existente.getByLabel("Tipo nombre").selectOption("Long")
  await page.getByText("Modelo UML canónico (JSON)").click()
  const json = page.locator(".canonical-json pre")
  await expect(json).toContainText('"tipo": "Long"')
  await expect(json).toContainText('"visibilidad": "privada"')
  await page.getByTestId("inspector-propiedades").getByRole("button", { name: "+ Agregar método" }).click()
  const nuevoMetodo = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Nuevo método" })
  await nuevoMetodo.getByLabel("Nombre").fill("cambiarNombre")
  await nuevoMetodo.getByLabel("Tipo de retorno").selectOption("void")
  await nuevoMetodo.getByRole("button", { name: "Confirmar método" }).click()
  const metodo = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Método cambiarNombre" })
  await metodo.getByRole("button", { name: "Parámetros" }).click()
  await metodo.getByRole("button", { name: "+ Agregar parámetro" }).click()
  const parametro = metodo.getByRole("group", { name: "Nuevo parámetro" })
  await parametro.getByLabel("Nombre").fill("nombre")
  await parametro.getByLabel("Tipo").selectOption("String")
  await parametro.getByRole("button", { name: "Confirmar parámetro" }).click()
  await expect(page.locator(".react-flow__node").filter({ hasText: "cambiarNombre(nombre: String): void" })).toBeVisible()
  await page.getByRole("button", { name: "Guardar" }).click()
  await page.getByRole("button", { name: "Mis proyectos" }).click()
  await abrirProyectoE2E(page, proyecto)
  await page.locator(".react-flow__node").filter({ hasText: "Cliente" }).click()
  await page.getByText("Modelo UML canónico (JSON)").click()
  await expect(page.locator(".canonical-json pre")).toContainText('"visibilidad": "privada"')
  await expect(page.locator(".canonical-json pre")).toContainText('"tipo": "Long"')
  await expect(page.locator(".canonical-json pre")).toContainText('"nombre": "cambiarNombre"')
  await expect(page.locator(".canonical-json pre")).toContainText('"tipoRetorno": "void"')
  await expect(page.locator(".react-flow__node").filter({ hasText: "cambiarNombre(nombre: String): void" })).toBeVisible()
  const metodoReabierto = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Método cambiarNombre" })
  await expect(metodoReabierto.getByRole("button", { name: "Eliminar método cambiarNombre" })).toBeVisible()
  await metodoReabierto.getByRole("button", { name: "Eliminar método cambiarNombre" }).click()
  await expect(page.getByTestId("inspector-propiedades").getByRole("group", { name: "Método cambiarNombre" })).toHaveCount(0)
  await expect(page.locator(".react-flow__node").filter({ hasText: "cambiarNombre" })).toHaveCount(0)
  await expect(page.locator(".canonical-json pre")).not.toContainText('"nombre": "cambiarNombre"')
  await page.getByRole("button", { name: "Guardar" }).click()
  await page.getByRole("button", { name: "Mis proyectos" }).click()
  await abrirProyectoE2E(page, proyecto)
  await expect(page.locator(".react-flow__node").filter({ hasText: "cambiarNombre" })).toHaveCount(0)
  await page.locator(".react-flow__node").filter({ hasText: "Cliente" }).click()
  await page.getByTestId("inspector-propiedades").getByRole("group", { name: "Atributo nombre" }).getByRole("button", { name: "Eliminar atributo nombre" }).click()
  await expect(page.locator(".canonical-json pre")).toContainText('"atributos": []')
})

test("relación guiada traduce Persona-Auto a extremos UML y persiste sin invertirlos", async ({ page }) => {
  const proyecto = await crearProyectoE2E(page, "Relación Persona Auto")
  await crearClaseNombradaE2E(page, "Persona")
  await crearClaseNombradaE2E(page, "Auto", 180)
  await page.getByTestId("inspector-propiedades").getByRole("button", { name: "+ Nueva relación" }).click()
  const relacion = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Nueva relación" })
  await relacion.getByLabel("Clase A", { exact: true }).selectOption({ label: "Persona" })
  await relacion.getByLabel("Clase B", { exact: true }).selectOption({ label: "Auto" })
  await relacion.getByLabel("Para una Persona, ¿cuántos Auto puede haber?").selectOption("0..*")
  await relacion.getByLabel("Para un Auto, ¿cuántas Persona puede haber?").selectOption("1")
  await relacion.getByLabel("Nombre de relación (opcional)").fill("tiene")
  await relacion.getByRole("button", { name: "Crear relación" }).click()
  const arista = page.locator(".react-flow__edge")
  await expect(arista).toHaveCount(1)
  await expect(arista).toBeVisible()
  await arista.click({ force: true })
  await expect(page.getByText("Relación seleccionada")).toBeVisible()
  await page.getByText("Modelo UML canónico (JSON)").click()
  const json = page.locator(".canonical-json pre")
  await expect(json).toContainText('"multiplicidadOrigen": "1"')
  await expect(json).toContainText('"multiplicidadDestino": "0..*"')
  await expect(json).toContainText('"nombre": "tiene"')
  const personaCaja = await page.locator(".react-flow__node").filter({ hasText: "Persona" }).boundingBox()
  const autoCaja = await page.locator(".react-flow__node").filter({ hasText: "Auto" }).boundingBox()
  const unoCaja = await arista.getByText("1", { exact: true }).boundingBox()
  const muchosCaja = await arista.getByText("*", { exact: true }).boundingBox()
  expect(personaCaja && autoCaja && unoCaja && muchosCaja).toBeTruthy()
  const centroX = (caja: NonNullable<typeof personaCaja>) => caja.x + caja.width / 2
  expect(Math.abs(centroX(unoCaja!) - centroX(personaCaja!))).toBeLessThan(Math.abs(centroX(unoCaja!) - centroX(autoCaja!)))
  expect(Math.abs(centroX(muchosCaja!) - centroX(autoCaja!))).toBeLessThan(Math.abs(centroX(muchosCaja!) - centroX(personaCaja!)))
  await page.getByRole("button", { name: "Guardar" }).click()
  await page.getByRole("button", { name: "Mis proyectos" }).click()
  await abrirProyectoE2E(page, proyecto)
  await page.getByText("Modelo UML canónico (JSON)").click()
  const jsonReabierto = page.locator(".canonical-json pre")
  await expect(jsonReabierto).toContainText('"claseOrigenId"')
  await expect(jsonReabierto).toContainText('"multiplicidadOrigen": "1"')
  await expect(jsonReabierto).toContainText('"multiplicidadDestino": "0..*"')
  await expect(page.locator(".react-flow__edge").getByText("1", { exact: true })).toBeVisible()
  await expect(page.locator(".react-flow__edge").getByText("*", { exact: true })).toBeVisible()

  await page.locator(".react-flow__edge").click({ force: true })
  const existente = page.getByTestId("inspector-propiedades").getByRole("group", { name: "Relación Persona → Auto" })
  await existente.getByLabel("Multiplicidad en este extremo Auto").selectOption("1..*")
  await expect(json).toContainText('"multiplicidadDestino": "1..*"')
  await existente.getByLabel("Multiplicidad en este extremo Persona").selectOption("0..*")
  await existente.getByLabel("Multiplicidad en este extremo Auto").selectOption("0..*")
  await expect(jsonReabierto).toContainText('"multiplicidadOrigen": "0..*"')
  await expect(jsonReabierto).toContainText('"multiplicidadDestino": "0..*"')
  await expect(page.getByText("No apto", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Guardar" }).click()
  await page.getByRole("button", { name: "Mis proyectos" }).click()
  await abrirProyectoE2E(page, proyecto)
  await page.getByText("Modelo UML canónico (JSON)").click()
  await expect(page.locator(".canonical-json pre")).toContainText('"multiplicidadOrigen": "0..*"')
  await expect(page.locator(".canonical-json pre")).toContainText('"multiplicidadDestino": "0..*"')
  await expect(page.locator(".react-flow__edge")).toHaveCount(1)
  await page.getByTestId("inspector-propiedades").getByRole("group", { name: "Relación Persona → Auto" }).getByRole("button", { name: "Eliminar relación" }).click()
  await expect(page.locator(".canonical-json pre")).toContainText('"relaciones": []')
})

test("idioma y tema persisten sin modificar el proyecto", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByRole("heading", { name: "Proyectos de modelado" })).toBeVisible()
  await page.getByLabel("Idioma").selectOption("en")
  await expect(page.getByRole("heading", { name: "Modeling projects" })).toBeVisible()
  await page.getByLabel("Project name").fill(`Language ${Date.now()}`)
  await page.getByRole("button", { name: "Create project" }).click()
  await expect(page.getByRole("heading", { name: "UML properties" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "From image" })).toBeVisible()
  await page.getByText("Canonical UML model (JSON)").click()
  await expect(page.locator(".canonical-json pre")).toContainText('"clases": []')
  await page.getByLabel("Theme").selectOption("oscuro")
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark")
  await page.reload()
  await expect(page.getByLabel("Language")).toHaveValue("en")
  await expect(page.getByLabel("Theme")).toHaveValue("oscuro")
  await expect(page.getByRole("heading", { name: "Modeling projects" })).toBeVisible()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark")
})
