import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react"
import type { ApollonLabels } from "@tumaet/apollon"

export type Idioma = "es" | "en"
export type Tema = "sistema" | "claro" | "oscuro"

const textos = {
  es: {
    "preferencias.idioma": "Idioma", "preferencias.tema": "Tema", "preferencias.es": "Español", "preferencias.en": "English", "preferencias.sistema": "Sistema", "preferencias.claro": "Claro", "preferencias.oscuro": "Oscuro",
    "proyectos.titulo": "Proyectos de modelado", "proyectos.descripcion": "Crea un proyecto o recupera uno guardado para comenzar a modelar.", "proyectos.crear": "Crear proyecto", "proyectos.nombre": "Nombre del proyecto", "proyectos.mios": "Mis proyectos", "proyectos.vacio": "No hay proyectos guardados.", "proyectos.abrir": "Abrir", "proyectos.actualizado": "Actualizado", "proyectos.guardado": "Guardado", "proyectos.sucio": "Cambios sin guardar", "proyectos.guardando": "Guardando…", "proyectos.guardar": "Guardar", "proyectos.confirmarSalida": "Hay cambios sin guardar. ¿Deseas volver a Mis proyectos?",
    "modelado.titulo": "Modelado manual de diagramas de clases", "modelado.descripcion": "Edición manual, colaborativa y asistida por IA sobre el modelo UML canónico.", "modelado.espacio": "Espacio de modelado UML", "modelado.error": "Error de integración del editor:",
    "propiedades.titulo": "Propiedades UML", "propiedades.seleccione": "Selecciona una clase para editarla de forma guiada.", "propiedades.clase": "Clase", "propiedades.nombreClase": "Nombre de clase", "propiedades.aplicarNombre": "Aplicar nombre", "propiedades.atributo": "Atributo", "propiedades.atributos": "Atributos", "propiedades.nuevoAtributo": "Nuevo atributo", "propiedades.nombre": "Nombre", "propiedades.tipo": "Tipo", "propiedades.visibilidad": "Visibilidad", "propiedades.privada": "Privada (-)", "propiedades.publica": "Pública (+)", "propiedades.sinVisibilidad": "Sin definir", "propiedades.agregarAtributo": "Agregar atributo", "propiedades.actualizarAtributo": "Actualizar atributo", "propiedades.mostrarNuevoAtributo": "+ Agregar atributo", "propiedades.confirmarAtributo": "Confirmar atributo", "propiedades.eliminarAtributo": "Eliminar atributo", "propiedades.cancelar": "Cancelar", "propiedades.noSoportado": "no soportado para generación", "propiedades.relacion": "Relación", "propiedades.relaciones": "Relaciones", "propiedades.nuevaRelacion": "Nueva relación", "propiedades.mostrarNuevaRelacion": "+ Nueva relación", "propiedades.crearRelacion": "Crear relación", "propiedades.eliminarRelacion": "Eliminar relación", "propiedades.tipoRelacion": "Tipo de relación", "propiedades.origen": "Origen", "propiedades.destino": "Destino", "propiedades.multiplicidad": "Multiplicidad", "propiedades.rolOpcional": "Rol (opcional)", "propiedades.seleccionar": "Seleccionar", "propiedades.agregarRelacion": "Agregar relación", "propiedades.actualizarRelacion": "Actualizar relación",
    "relacion.asociacion": "Asociación", "relacion.agregacion": "Agregación", "relacion.composicion": "Composición", "relacion.generalizacion": "Generalización", "multiplicidad.1": "1 — Exactamente uno", "multiplicidad.0..1": "0..1 — Cero o uno", "multiplicidad.0..*": "0..* — Cero o muchos", "multiplicidad.1..*": "1..* — Uno o muchos",
    "colaboracion.titulo": "Colaboración", "colaboracion.proyecto": "Proyecto compartido", "colaboracion.estado": "Estado", "colaboracion.participantes": "Participantes", "generacion.titulo": "Generación Spring Boot", "generacion.modelo": "Modelo UML", "generacion.generador": "Generador", "generacion.generar": "Generar backend Spring Boot", "generacion.generando": "Generando…", "generacion.valido": "Válido", "generacion.invalido": "Inválido", "generacion.apto": "Apto", "generacion.noApto": "No apto", "xmi.titulo": "Interoperabilidad XMI", "xmi.importar": "Importar XMI", "xmi.exportar": "Exportar XMI",
    "ia.titulo": "Asistente IA", "ia.instruccion": "Instrucción UML", "ia.placeholder": "Ej.: Crea una clase Cliente", "ia.enviar": "Enviar", "ia.nota": "Los cambios claros y válidos se aplican automáticamente, sin confirmación.", "voz.hablar": "🎙 Hablar", "voz.detener": "⏹ Detener", "voz.noDisponible": "Entrada de voz no disponible en este navegador.", "voz.reconocida": "Voz reconocida:",
    "imagen.titulo": "Desde imagen", "imagen.seleccionar": "Seleccionar imagen", "imagen.analizar": "Analizar imagen", "imagen.analizando": "Analizando imagen...", "imagen.candidato": "Modelo UML candidato", "imagen.agregar": "Agregar al diagrama", "imagen.cancelar": "Cancelar", "imagen.advertencias": "Advertencias", "imagen.nota": "La imagen se procesa mediante el servicio de IA configurado en el servidor. Nada cambia hasta confirmar.",
    "propiedades.nuevaClase": "Nueva clase", "propiedades.crearClase": "Crear clase", "propiedades.nombreClaseActual": "Nombre de la clase seleccionada", "propiedades.tipoClase": "Tipo de clase", "propiedades.normal": "Normal", "propiedades.asociativa": "Asociativa", "propiedades.convertirAsociativa": "Convertir en clase asociativa", "propiedades.nombreClaseAsociativa": "Nombre de clase asociativa", "propiedades.confirmarConversionAsociativa": "Convertir relación", "propiedades.claseA": "Clase A", "propiedades.claseB": "Clase B", "propiedades.todo": "Todo", "propiedades.parte": "Parte", "propiedades.subclase": "Subclase", "propiedades.superclase": "Superclase", "propiedades.nombreRelacion": "Nombre de relación (opcional)", "propiedades.relacionSeleccionada": "Relación seleccionada", "metodos.titulo": "Métodos", "metodos.metodo": "Método", "metodos.nuevo": "Nuevo método", "metodos.agregar": "+ Agregar método", "metodos.confirmar": "Confirmar método", "metodos.eliminar": "Eliminar método", "metodos.retorno": "Tipo de retorno", "metodos.parametros": "Parámetros", "metodos.parametro": "Parámetro", "metodos.nuevoParametro": "Nuevo parámetro", "metodos.agregarParametro": "+ Agregar parámetro", "metodos.confirmarParametro": "Confirmar parámetro", "metodos.eliminarParametro": "Eliminar parámetro", "proyectos.guardadoCorrecto": "Proyecto guardado correctamente.",
    "propiedades.cantidadDestinoPorOrigen": "Para una {origen}, ¿cuántos {destino} puede haber?", "propiedades.cantidadOrigenPorDestino": "Para un {destino}, ¿cuántas {origen} puede haber?", "propiedades.multiplicidadExtremo": "Multiplicidad en este extremo", "propiedades.explicacionExtremoOrigen": "Cada {destino} se relaciona con esta cantidad de {origen}.", "propiedades.explicacionExtremoDestino": "Cada {origen} se relaciona con esta cantidad de {destino}.", "propiedades.listaRelaciones": "Lista de relaciones", "propiedades.relacionesRegistradas": "relaciones; selecciona una para editarla",
    "ia.interpretando": "Interpretando...", "ia.aplicando": "Aplicando...", "ia.listo": "Listo", "ia.error": "Error", "ia.instruccionRequerida": "Escribe una instrucción de modelado.", "ia.errorProcesamiento": "No se pudo procesar la instrucción con IA.",
    "voz.solicitando": "Solicitando acceso al micrófono...", "voz.escuchando": "Escuchando...", "voz.transcribiendo": "Transcribiendo...", "voz.sinInstruccion": "No se detectó una instrucción de voz.", "voz.errorMicrofono": "No se pudo acceder al micrófono.", "voz.errorTranscripcion": "No se pudo transcribir el audio.",
    "imagen.seleccionada": "Seleccionada", "imagen.vistaPrevia": "Vista previa de la imagen seleccionada", "imagen.candidatoAria": "Modelo UML candidato", "imagen.clasesDetectadas": "Clases detectadas", "imagen.relacionesDetectadas": "Relaciones detectadas", "imagen.sinAtributos": "Sin atributos visibles.", "imagen.roles": "roles", "imagen.agregado": "El candidato se agregó al diagrama.", "imagen.descartado": "Candidato descartado sin modificar el diagrama.", "imagen.errorAnalisis": "No se pudo analizar la imagen.", "imagen.errorAplicacion": "No se pudo agregar el candidato.", "imagen.tipoNoVisible": "tipo no visible", "imagen.tipoNoSoportado": "tipo no soportado", "imagen.noImportara": "no se importará", "imagen.atributo": "El atributo", "imagen.deClase": "de", "imagen.sinTipoDetalle": "no se importará porque no tiene un tipo visible.",
    "colaboracion.conectando": "conectando", "colaboracion.conectado": "conectado", "colaboracion.desconectado": "desconectado", "colaboracion.error": "error", "colaboracion.lista": "Participantes conectados", "colaboracion.tu": "Tú", "colaboracion.nota": "Sala efímera derivada del proyecto; el guardado persistente continúa siendo explícito.",
    "generacion.exito": "Backend generado y descargado.", "generacion.error": "Error", "generacion.errorGenerar": "No se pudo generar el backend.",
    "xmi.listo": "Listo", "xmi.confirmar": "Importar este XMI reemplazará el diagrama actual.", "xmi.importando": "Importando...", "xmi.importado": "Importado correctamente", "xmi.exportando": "Exportando...", "xmi.exportado": "XMI exportado", "xmi.errorImportar": "No se pudo importar el XMI.", "xmi.errorExportar": "No se pudo exportar el XMI.", "xmi.advertencias": "Advertencias de importación", "xmi.error": "Error",
    "preferencias.aria": "Preferencias de interfaz", "editor.fallo": "No se pudo inicializar el editor UML", "editor.recargar": "Recargar editor",
    "inspector.evidencia": "Evidencia de integración", "inspector.titulo": "Inspector de Modelo — Desarrollo", "inspector.noDisponible": "Modelo no disponible", "inspector.esperando": "Esperando el modelo del editor...", "inspector.id": "Id del modelo", "inspector.version": "Versión del modelo", "inspector.tipoDiagrama": "Tipo de diagrama", "inspector.nodos": "Nodos", "inspector.clases": "Clases", "inspector.relaciones": "Relaciones", "inspector.apollonJson": "Modelo Apollon (JSON)", "inspector.canonico": "UML canónico", "inspector.atributos": "Atributos", "inspector.advertenciasAdaptacion": "Advertencias de adaptación", "inspector.canonicoJson": "Modelo UML canónico (JSON)", "inspector.validacion": "Validación", "inspector.estado": "Estado", "inspector.valido": "Válido", "inspector.invalido": "Inválido", "inspector.errores": "Errores", "inspector.advertencias": "Advertencias", "inspector.diagnosticos": "Diagnósticos",
    "paquete.proyectos": "Gestión de Proyectos",
  },
  en: {
    "preferencias.idioma": "Language", "preferencias.tema": "Theme", "preferencias.es": "Español", "preferencias.en": "English", "preferencias.sistema": "System", "preferencias.claro": "Light", "preferencias.oscuro": "Dark",
    "proyectos.titulo": "Modeling projects", "proyectos.descripcion": "Create a project or recover saved work to start modeling.", "proyectos.crear": "Create project", "proyectos.nombre": "Project name", "proyectos.mios": "My projects", "proyectos.vacio": "No saved projects.", "proyectos.abrir": "Open", "proyectos.actualizado": "Updated", "proyectos.guardado": "Saved", "proyectos.sucio": "Unsaved changes", "proyectos.guardando": "Saving…", "proyectos.guardar": "Save", "proyectos.confirmarSalida": "There are unsaved changes. Return to My projects?",
    "modelado.titulo": "Manual class-diagram modeling", "modelado.descripcion": "Manual, collaborative and AI-assisted editing over the canonical UML model.", "modelado.espacio": "UML modeling workspace", "modelado.error": "Editor integration error:",
    "propiedades.titulo": "UML properties", "propiedades.seleccione": "Select a class to edit it with guided controls.", "propiedades.clase": "Class", "propiedades.nombreClase": "Class name", "propiedades.aplicarNombre": "Apply name", "propiedades.atributo": "Attribute", "propiedades.atributos": "Attributes", "propiedades.nuevoAtributo": "New attribute", "propiedades.nombre": "Name", "propiedades.tipo": "Type", "propiedades.visibilidad": "Visibility", "propiedades.privada": "Private (-)", "propiedades.publica": "Public (+)", "propiedades.sinVisibilidad": "Not defined", "propiedades.agregarAtributo": "Add attribute", "propiedades.actualizarAtributo": "Update attribute", "propiedades.mostrarNuevoAtributo": "+ Add attribute", "propiedades.confirmarAtributo": "Confirm attribute", "propiedades.eliminarAtributo": "Delete attribute", "propiedades.cancelar": "Cancel", "propiedades.noSoportado": "unsupported for generation", "propiedades.relacion": "Relationship", "propiedades.relaciones": "Relationships", "propiedades.nuevaRelacion": "New relationship", "propiedades.mostrarNuevaRelacion": "+ New relationship", "propiedades.crearRelacion": "Create relationship", "propiedades.eliminarRelacion": "Delete relationship", "propiedades.tipoRelacion": "Relationship type", "propiedades.origen": "Source", "propiedades.destino": "Target", "propiedades.multiplicidad": "Multiplicity", "propiedades.rolOpcional": "Role (optional)", "propiedades.seleccionar": "Select", "propiedades.agregarRelacion": "Add relationship", "propiedades.actualizarRelacion": "Update relationship",
    "relacion.asociacion": "Association", "relacion.agregacion": "Aggregation", "relacion.composicion": "Composition", "relacion.generalizacion": "Generalization", "multiplicidad.1": "1 — Exactly one", "multiplicidad.0..1": "0..1 — Zero or one", "multiplicidad.0..*": "0..* — Zero or many", "multiplicidad.1..*": "1..* — One or many",
    "colaboracion.titulo": "Collaboration", "colaboracion.proyecto": "Shared project", "colaboracion.estado": "Status", "colaboracion.participantes": "Participants", "generacion.titulo": "Spring Boot generation", "generacion.modelo": "UML model", "generacion.generador": "Generator", "generacion.generar": "Generate Spring Boot backend", "generacion.generando": "Generating…", "generacion.valido": "Valid", "generacion.invalido": "Invalid", "generacion.apto": "Ready", "generacion.noApto": "Not ready", "xmi.titulo": "XMI interoperability", "xmi.importar": "Import XMI", "xmi.exportar": "Export XMI",
    "ia.titulo": "AI assistant", "ia.instruccion": "UML instruction", "ia.placeholder": "E.g. Create a Customer class", "ia.enviar": "Send", "ia.nota": "Clear, valid changes are applied automatically without confirmation.", "voz.hablar": "🎙 Speak", "voz.detener": "⏹ Stop", "voz.noDisponible": "Voice input is not available in this browser.", "voz.reconocida": "Recognized voice:",
    "imagen.titulo": "From image", "imagen.seleccionar": "Select image", "imagen.analizar": "Analyze image", "imagen.analizando": "Analyzing image…", "imagen.candidato": "Candidate UML model", "imagen.agregar": "Add to diagram", "imagen.cancelar": "Cancel", "imagen.advertencias": "Warnings", "imagen.nota": "The image is processed by the server-side AI service. Nothing changes before confirmation.",
    "propiedades.nuevaClase": "New class", "propiedades.crearClase": "Create class", "propiedades.nombreClaseActual": "Selected class name", "propiedades.tipoClase": "Class type", "propiedades.normal": "Normal", "propiedades.asociativa": "Associative", "propiedades.convertirAsociativa": "Convert to associative class", "propiedades.nombreClaseAsociativa": "Associative class name", "propiedades.confirmarConversionAsociativa": "Convert relationship", "propiedades.claseA": "Class A", "propiedades.claseB": "Class B", "propiedades.todo": "Whole", "propiedades.parte": "Part", "propiedades.subclase": "Subclass", "propiedades.superclase": "Superclass", "propiedades.nombreRelacion": "Relationship name (optional)", "propiedades.relacionSeleccionada": "Selected relationship", "metodos.titulo": "Methods", "metodos.metodo": "Method", "metodos.nuevo": "New method", "metodos.agregar": "+ Add method", "metodos.confirmar": "Confirm method", "metodos.eliminar": "Delete method", "metodos.retorno": "Return type", "metodos.parametros": "Parameters", "metodos.parametro": "Parameter", "metodos.nuevoParametro": "New parameter", "metodos.agregarParametro": "+ Add parameter", "metodos.confirmarParametro": "Confirm parameter", "metodos.eliminarParametro": "Delete parameter", "proyectos.guardadoCorrecto": "Project saved successfully.",
    "propiedades.cantidadDestinoPorOrigen": "For one {origen}, how many {destino} instances may there be?", "propiedades.cantidadOrigenPorDestino": "For one {destino}, how many {origen} instances may there be?", "propiedades.multiplicidadExtremo": "Multiplicity at this end", "propiedades.explicacionExtremoOrigen": "Each {destino} is related to this many {origen} instances.", "propiedades.explicacionExtremoDestino": "Each {origen} is related to this many {destino} instances.", "propiedades.listaRelaciones": "Relationship list", "propiedades.relacionesRegistradas": "relationships; select one to edit it",
    "ia.interpretando": "Interpreting...", "ia.aplicando": "Applying...", "ia.listo": "Ready", "ia.error": "Error", "ia.instruccionRequerida": "Enter a modeling instruction.", "ia.errorProcesamiento": "The AI instruction could not be processed.",
    "voz.solicitando": "Requesting microphone access...", "voz.escuchando": "Listening...", "voz.transcribiendo": "Transcribing...", "voz.sinInstruccion": "No voice instruction was detected.", "voz.errorMicrofono": "Microphone access failed.", "voz.errorTranscripcion": "The audio could not be transcribed.",
    "imagen.seleccionada": "Selected", "imagen.vistaPrevia": "Preview of the selected image", "imagen.candidatoAria": "Candidate UML model", "imagen.clasesDetectadas": "Classes detected", "imagen.relacionesDetectadas": "Relationships detected", "imagen.sinAtributos": "No visible attributes.", "imagen.roles": "roles", "imagen.agregado": "The candidate was added to the diagram.", "imagen.descartado": "Candidate discarded without changing the diagram.", "imagen.errorAnalisis": "The image could not be analyzed.", "imagen.errorAplicacion": "The candidate could not be added.", "imagen.tipoNoVisible": "type not visible", "imagen.tipoNoSoportado": "unsupported type", "imagen.noImportara": "will not be imported", "imagen.atributo": "The attribute", "imagen.deClase": "of", "imagen.sinTipoDetalle": "will not be imported because it has no visible type.",
    "colaboracion.conectando": "connecting", "colaboracion.conectado": "connected", "colaboracion.desconectado": "disconnected", "colaboracion.error": "error", "colaboracion.lista": "Connected participants", "colaboracion.tu": "You", "colaboracion.nota": "Ephemeral room derived from the project; durable saving remains explicit.",
    "generacion.exito": "Backend generated and downloaded.", "generacion.error": "Error", "generacion.errorGenerar": "The backend could not be generated.",
    "xmi.listo": "Ready", "xmi.confirmar": "Importing this XMI will replace the current diagram.", "xmi.importando": "Importing...", "xmi.importado": "Imported successfully", "xmi.exportando": "Exporting...", "xmi.exportado": "XMI exported", "xmi.errorImportar": "The XMI could not be imported.", "xmi.errorExportar": "The XMI could not be exported.", "xmi.advertencias": "Import warnings", "xmi.error": "Error",
    "preferencias.aria": "Interface preferences", "editor.fallo": "The UML editor could not be initialized", "editor.recargar": "Reload editor",
    "inspector.evidencia": "Integration evidence", "inspector.titulo": "Model Inspector — Development", "inspector.noDisponible": "Model unavailable", "inspector.esperando": "Waiting for the editor model...", "inspector.id": "Model ID", "inspector.version": "Model version", "inspector.tipoDiagrama": "Diagram type", "inspector.nodos": "Nodes", "inspector.clases": "Classes", "inspector.relaciones": "Relationships", "inspector.apollonJson": "Apollon model (JSON)", "inspector.canonico": "Canonical UML", "inspector.atributos": "Attributes", "inspector.advertenciasAdaptacion": "Adapter warnings", "inspector.canonicoJson": "Canonical UML model (JSON)", "inspector.validacion": "Validation", "inspector.estado": "Status", "inspector.valido": "Valid", "inspector.invalido": "Invalid", "inspector.errores": "Errors", "inspector.advertencias": "Warnings", "inspector.diagnosticos": "Diagnostics",
    "paquete.proyectos": "Project Management",
  },
} as const

export type ClaveTexto = keyof typeof textos.es
interface Preferencias { idioma: Idioma; tema: Tema; temaAplicado: "light" | "dark"; establecerIdioma: (v: Idioma) => void; establecerTema: (v: Tema) => void; t: (clave: ClaveTexto) => string }
const Contexto = createContext<Preferencias | null>(null)
const leerIdioma = (): Idioma => localStorage.getItem("sw1.idioma") === "en" ? "en" : "es"
const leerTema = (): Tema => { const v = localStorage.getItem("sw1.tema"); return v === "claro" || v === "oscuro" ? v : "sistema" }

export function ProveedorPreferenciasUI({ children }: { children: ReactNode }) {
  const [idioma, establecerIdioma] = useState<Idioma>(leerIdioma)
  const [tema, establecerTema] = useState<Tema>(leerTema)
  const [sistemaOscuro, establecerSistemaOscuro] = useState(() => matchMedia("(prefers-color-scheme: dark)").matches)
  const temaAplicado = tema === "sistema" ? (sistemaOscuro ? "dark" : "light") : tema === "oscuro" ? "dark" : "light"
  useEffect(() => { const consulta = matchMedia("(prefers-color-scheme: dark)"); const cambiar = (e: MediaQueryListEvent) => establecerSistemaOscuro(e.matches); consulta.addEventListener("change", cambiar); return () => consulta.removeEventListener("change", cambiar) }, [])
  useEffect(() => { document.documentElement.lang = idioma; localStorage.setItem("sw1.idioma", idioma) }, [idioma])
  useEffect(() => { document.documentElement.dataset.theme = temaAplicado; localStorage.setItem("sw1.tema", tema) }, [tema, temaAplicado])
  const valor = useMemo<Preferencias>(() => ({ idioma, tema, temaAplicado, establecerIdioma, establecerTema, t: (clave) => textos[idioma][clave] }), [idioma, tema, temaAplicado])
  return <Contexto.Provider value={valor}>{children}</Contexto.Provider>
}

const preferenciasPredeterminadas: Preferencias = { idioma: "es", tema: "sistema", temaAplicado: "light", establecerIdioma: () => undefined, establecerTema: () => undefined, t: (clave) => textos.es[clave] }
export function usarPreferenciasUI(): Preferencias { return useContext(Contexto) ?? preferenciasPredeterminadas }

export function ControlesPreferencias() {
  const { idioma, tema, establecerIdioma, establecerTema, t } = usarPreferenciasUI()
  return <aside className="ui-preferences" aria-label={t("preferencias.aria")}><label>{t("preferencias.idioma")}<select aria-label={t("preferencias.idioma")} value={idioma} onChange={(e) => establecerIdioma(e.target.value as Idioma)}><option value="es">{t("preferencias.es")}</option><option value="en">{t("preferencias.en")}</option></select></label><label>{t("preferencias.tema")}<select aria-label={t("preferencias.tema")} value={tema} onChange={(e) => establecerTema(e.target.value as Tema)}><option value="sistema">{t("preferencias.sistema")}</option><option value="claro">{t("preferencias.claro")}</option><option value="oscuro">{t("preferencias.oscuro")}</option></select></label></aside>
}

export function etiquetasApollon(idioma: Idioma): Partial<ApollonLabels> {
  if (idioma === "en") return {}
  return { class: "Clase", classType: "Tipo de clase", abstractClass: "Clase abstracta", attributes: "Atributos", attribute: "Atributo", methods: "Métodos", method: "Método", edge: "Relación", style: "Estilo", edgeType: "Tipo de relación", source: "Origen", target: "Destino", multiplicityLabel: (n) => `Multiplicidad en ${n}`, roleLabel: (n) => `Rol en ${n} (opcional)`, editElement: "Editar elemento", editEdge: "Editar relación", deleteElement: "Eliminar elemento", deleteEdge: "Eliminar relación", association: "Asociación", aggregation: "Agregación", composition: "Composición", inheritance: "Generalización", newAttribute: "Nuevo atributo", addAttribute: "Agregar atributo", deleteAttribute: "Eliminar atributo", namePlaceholder: "Nombre" }
}
